name: Kind Test

on:
  workflow_dispatch:
    inputs:
      kindVersion:
        description: The kind version
        default: 0.20.0 # Kubernetes version: 1.27.X
  pull_request:
    branches:
      - main

env:
  KIND_VERSION: ${{ github.event.inputs.kindVersion || vars.KIND_VERSION }}

jobs:
  kind_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup kind
        uses: helm/kind-action@fa81e57adff234b2908110485695db0f181f3c67 # v1.7.0
        with:
          wait: 2m
          version: v${{ env.KIND_VERSION }}

---

name: Reusable kind Test

on:
  workflow_dispatch:
    inputs:
      kindVersion:
        description: The kind version
        default: 0.20.0 # Kubernetes version: 1.27.X
  pull_request:
    branches:
      - main
  workflow_call: 

jobs:
  reusable_kind_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup kind
        uses: helm/kind-action@fa81e57adff234b2908110485695db0f181f3c67 # v1.7.0
        with:
          wait: 2m
          version: v${{ env.KIND_VERSION }}
