name: Kind Test

on:
  workflow_dispatch:
    inputs:
      kindVersion:
        description: The kind version
        default: 0.20.0 # Kubernetes version: 1.27.X
  pull_request:
    branches:
      - main

env:
  KIND_VERSION: ${{ github.event.inputs.kindVersion || vars.KIND_VERSION }}

jobs:
  kind_test:
    uses: sheneska/hack-week-reuasble-workflow/.github/workflows/reuasble_kind_test.yml@add-simpleworkflow