name: Reusable kind Test

on:
  workflow_call: 

jobs:
  reusable_kind_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup kind
        uses: helm/kind-action@fa81e57adff234b2908110485695db0f181f3c67 # v1.7.0
        with:
          wait: 2m
          version: v${{ env.KIND_VERSION }}
